import type { BriefingOutput, ExpertiseOutput, JiraEvidenceItem, ConfluenceEvidenceItem } from '@/types'

export const MOCK_BRIEFING: BriefingOutput = {
  projectName: 'Mock Project',
  oneLiner: 'A mock project used for local development and testing without an API key.',
  sections: {
    summary:
      'This is a mock briefing generated by Teller\'s mock mode. It allows the full app flow to be tested — streaming, progress steps, history, rating, export — without an Anthropic API key.',
    whyItExists:
      'Engineers need to be able to test the app locally when the API key is unavailable or being rotated. Mock mode provides a realistic response without incurring API costs or requiring credentials.',
    currentState: {
      status: 'in-progress',
      notes: 'Mock mode is active. Set TELLER_MOCK=true in .env.local to enable.',
      tickets: ['FAB2-001', 'FAB2-002'],
    },
    howItWorks:
      'When TELLER_MOCK=true, runClaude() and runClaudeTool() are replaced with stub implementations that return these fixtures after a short artificial delay. All other app logic (ingest, git, SSE streaming) runs for real.',
    dependencies: [
      { name: 'Next.js', relationship: 'Framework', note: 'v16, App Router' },
      { name: 'Anthropic SDK', relationship: 'AI transport', note: 'Bypassed in mock mode' },
      { name: 'Claude CLI', relationship: 'MCP tool runner', note: 'Bypassed in mock mode' },
    ],
    whoIsAffected:
      'Internal Immediate Media engineers using Teller locally. No end users — this is a developer tool.',
    risks: [
      { risk: 'Mock responses may drift from real response shape if types change', severity: 'low' },
      { risk: 'Artificial delays may not reflect real latency for UX testing', severity: 'low' },
    ],
    whoToTalkTo:
      'Sam Pepper (AdTech) owns this repo. Check git log for recent contributors.',
    upcomingWork:
      'Parallel Atlassian evidence gathering, progressive streaming of partial results, Confluence URL input field.',
    glossary: [
      { term: 'MCP', definition: 'Model Context Protocol — allows Claude CLI to call external tools like Jira and Confluence search.' },
      { term: 'SSE', definition: 'Server-Sent Events — the streaming transport used to push progress updates and results to the browser.' },
    ],
  },
}

export const MOCK_EXPERTISE: ExpertiseOutput = {
  question: 'Mock question for testing',
  maintainers: [
    {
      name: 'Sam Pepper',
      email: 'sam.pepper@immediate.co.uk',
      confidence: 'high',
      rationale: 'Most recent commits across all repos. Active Jira assignee on related tickets.',
      evidence: [
        '12 commits in the last 90 days across project-teller and ad-manager repos',
        'Assigned to FAB2-001 (active sprint)',
        'Author of WCPP Confluence page on AdTech architecture',
      ],
    },
    {
      name: 'Alice Chen',
      email: 'alice.chen@immediate.co.uk',
      confidence: 'medium',
      rationale: 'Confluence page author with recent edits. Some Jira involvement.',
      evidence: [
        'Last edited the relevant Confluence page 3 weeks ago',
        'Reporter on FAB2-002',
      ],
    },
  ],
  makers: [
    {
      name: 'Bob Williams',
      email: 'bob.williams@immediate.co.uk',
      confidence: 'medium',
      rationale: 'High historical commit volume in the relevant area, though no recent activity.',
      evidence: [
        '47 commits in stitcher repo (2022–2023)',
        'Wrote original implementation of ad-manager.js module',
      ],
    },
  ],
  noClearMatch: false,
  summary:
    'Sam Pepper is the strongest current contact — active in both code and Jira. Alice Chen is a good secondary option for documentation questions. Bob Williams built the original system but has not been active recently.',
}

export const MOCK_JIRA_ITEMS: JiraEvidenceItem[] = [
  {
    key: 'FAB2-001',
    summary: 'Implement parallel Atlassian evidence gathering in Teller',
    status: 'In Progress',
    assignee: 'Sam Pepper',
    reporter: 'Sam Pepper',
    url: 'https://immediateco.atlassian.net/browse/FAB2-001',
    updated: '2026-07-10',
  },
  {
    key: 'FAB2-002',
    summary: 'Add Confluence URL input to Project Teller briefing form',
    status: 'To Do',
    assignee: undefined,
    reporter: 'Alice Chen',
    url: 'https://immediateco.atlassian.net/browse/FAB2-002',
    updated: '2026-07-08',
  },
]

export const MOCK_CONFLUENCE_ITEMS: ConfluenceEvidenceItem[] = [
  {
    id: '123456',
    title: 'AdTech Architecture Overview',
    spaceKey: 'WCPP',
    author: 'Alice Chen',
    url: 'https://immediateco.atlassian.net/wiki/spaces/WCPP/pages/123456',
    lastModified: '2026-06-20',
  },
  {
    id: '789012',
    title: 'Stitcher Ad Manager — Technical Reference',
    spaceKey: 'WCPP',
    author: 'Bob Williams',
    url: 'https://immediateco.atlassian.net/wiki/spaces/WCPP/pages/789012',
    lastModified: '2025-11-14',
  },
]

/** Artificial delay to simulate real API latency in mock mode */
export function mockDelay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
